export const ritualCatalog = {
  "Skin Care": [
    "Double cleanse at night",
    "Gentle gel cleanse in the morning",
    "Hydrating toner layering",
    "Vitamin C serum application",
    "Niacinamide balancing treatment",
    "Ceramide barrier moisturizer",
    "Daily broad-spectrum SPF 50",
    "Weekly enzyme exfoliation",
    "Cooling under-eye patches",
    "Face massage with gua sha",
    "Overnight moisture sleeping mask",
    "Lip scrub and balm ritual",
    "Targeted spot treatment",
    "Neck and chest skincare extension",
    "Weekly sheet mask hydration",
  ],
  Makeup: [
    "Hydrating primer prep",
    "Color-correct base routine",
    "Lightweight skin tint blend",
    "Concealer spot-correct pass",
    "Cream blush layering",
    "Soft contour definition",
    "Highlighter glow placement",
    "Brow shape and set",
    "Neutral eye shadow blend",
    "Tightline eyeliner technique",
    "Lengthening mascara coat",
    "Lip liner + gloss combo",
    "Makeup setting mist seal",
    "Midday touch-up ritual",
    "Gentle makeup removal sequence",
  ],
  "Hair Care": [
    "Scalp oil pre-wash massage",
    "Sulfate-free cleansing routine",
    "Deep conditioner once weekly",
    "Protein mask treatment",
    "Leave-in conditioner application",
    "Heat protectant before styling",
    "Microfiber towel drying",
    "Low-heat blowout method",
    "Weekly clarifying wash",
    "Silk pillowcase protection",
    "Overnight braid preservation",
    "Frizz-control serum finish",
    "Edge and baby hair care",
    "Split-end trimming schedule",
    "Scalp tonic hydration",
  ],
  "Nail Care": [
    "Gentle nail cleansing",
    "Weekly nail shaping session",
    "Cuticle softening soak",
    "Cuticle oil massage",
    "Strengthening base coat",
    "Breathable polish application",
    "Top-coat sealing routine",
    "Nail bed hydration cream",
    "Buffing for natural shine",
    "Hands SPF protection",
    "Night hand mask ritual",
    "Biotin-support meal planning",
    "Acetone-free polish removal",
    "Sanitized tool care routine",
    "Hangnail prevention treatment",
  ],
  Hygiene: [
    "Morning body cleanse",
    "Evening refresh shower",
    "Gentle body exfoliation",
    "Moisturizing body lotion",
    "Underarm care routine",
    "Oral care two-minute brushing",
    "Tongue and floss ritual",
    "Hydrating hand-wash follow-up",
    "Clean towel replacement cycle",
    "Workout hygiene reset",
    "Intimate care best-practice cleanse",
    "Foot wash and dry ritual",
    "Fresh clothing rotation",
    "Bedding hygiene schedule",
    "Nighttime oral care complete",
  ],
  Wellness: [
    "Morning breathwork set",
    "5-minute gratitude journaling",
    "Gentle wake-up stretches",
    "Hydration tracking habit",
    "Balanced breakfast ritual",
    "Midday movement break",
    "Posture reset reminder",
    "Sunlight exposure walk",
    "Digital detox interval",
    "Evening herbal tea unwind",
    "Guided meditation session",
    "Foam rolling tension release",
    "Sleep wind-down routine",
    "Weekly self-reflection check-in",
    "Affirmation and intention setting",
  ],
};
